spring.application.name=marketspring

spring.datasource.url=jdbc:postgresql://localhost:5432/marketspring
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

server.port=8080

logging.level.root=INFO